from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from io import BytesIO
from datetime import datetime
from ..models.models import Document, Edit, User
from typing import List

class ReportService:
    @staticmethod
    def generate_audit_report(document: Document, user: User, edits: List[Edit]) -> BytesIO:
        """
        Generates a PDF audit report of all changes made to a document.
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        elements = []

        # Title
        elements.append(Paragraph(f"Audit Report: {document.filename}", styles['Title']))
        elements.append(Spacer(1, 12))

        # Document Info Table
        info_data = [
            ["Document ID", str(document.id)],
            ["Owner", user.email],
            ["Import Date", document.created_at.strftime("%Y-%m-%d %H:%M:%S")],
            ["Type", "Scanned PDF" if document.is_scanned else "Text PDF"],
            ["Total Pages", str(document.page_count)],
            ["Total Edits", str(len(edits))],
            ["Report Date", datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
        ]
        
        info_table = Table(info_data, colWidths=[100, 300])
        info_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))
        elements.append(info_table)
        elements.append(Spacer(1, 24))

        # Edits Section
        elements.append(Paragraph("Modification History", styles['Heading2']))
        elements.append(Spacer(1, 12))

        if not edits:
            elements.append(Paragraph("No modifications recorded.", styles['Normal']))
        else:
            edit_data = [["Page", "Type", "Details", "Date"]]
            for edit in edits:
                details = f"{edit.edit_type.replace('_', ' ').capitalize()}"
                if edit.new_value:
                    details += f": '{edit.new_value}'"
                
                edit_data.append([
                    str(edit.page_number + 1),
                    edit.edit_type,
                    details,
                    edit.created_at.strftime("%H:%M:%S")
                ])
            
            edit_table = Table(edit_data, colWidths=[40, 80, 200, 80])
            edit_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('PADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(edit_table)

        # Footer
        elements.append(Spacer(1, 48))
        footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey)
        elements.append(Paragraph("This report was automatically generated by PDF Fixer Pro. All modifications are logged for traceability and legitimate usage compliance.", footer_style))

        doc.build(elements)
        buffer.seek(0)
        return buffer
